= AeroGear Showcase Application

Example application using AeroGear Mobile Services.

== Implementation

Implementation includes:

- Integration with AeroGear Mobile Services
- Ionic 4 Angular frontend backed by Cordova
- A Node.js GraphQL Server that implements a sample `Tasks` workflow
- Authentication provided by Keycloak integration on the server and client side
- GraphQL Subscriptions backed by an MQTT broker

=== GraphQL Client

The mobile application uses https://github.com/aerogear/aerogear-js-sdk/tree/master/packages/sync[Voyager Client] to provide additional offline capabilities on top of Apollo GraphQL.

=== GraphQL Server

The GraphQL server uses https://github.com/aerogear/voyager-server[Voyager Server] to provide GraphQL capabilities along with security, monitoring and tools to simplify GraphQL API development.

== Getting Started

Requirements:

- Docker
- Node.js 6.x or above to run server
- (optional) access to a running OpenShift instance

=== Running the server

. Start the Postgres database and the MQTT broker
+
```shell
cd ./server
docker-compose up
```

. Start the server
+
```shell
npm install
npm run dev
```
+
[NOTE]
====
If Keycloak integration is enabled on the server, and the Keycloak server is running using self-signed certificate, please make sure set this environment variable before running the server:

```shell
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
====

=== Running the Server with the Keycloak Integration

Follow these instructions to set up Keycloak for Authentication/Authorization.

. Start Keycloak Server
+
```shell
npm run keycloak
```

. Configure the Keycloak Server
+
```shell
npm run keycloak:init
```

This command creates the necessary resources in Keycloak and prints instructions *you must follow to enable the integration.* 

Follow the instructions and copy the JSON configurations to the appropriate location.
The showcase app and server will read these configurations and the integration will be enabled when they are started.

By default, two users that can log into the application are created.

- username: `developer`, password: `developer`
- username: `admin`, password: `admin`

=== Running the Server on OpenShift 

. Log into your OpenShift instance with the `oc login` command.
. Deploy the Server with PostgreSQL
Templates can be found in https://github.com/aerogear/datasync-deployment repository.


+
```shell
git clone https://github.com/aerogear/datasync-deployment
cd datasync-deployment
oc new-app -f openshift/datasync-showcase.yml
```

. To deprovision all of the resources from the template, run
+
```shell
oc delete all -l app=ionic-showcase-server \
&& oc delete secret -l app=ionic-showcase-server \
&& oc delete pvc -l app=ionic-showcase-server
```

=== Running the Client

. Install Cordova & Ionic 4
+
```shell
npm install -g cordova ionic@4
```

. Install dependencies
+
```shell
npm install
```

. Browse Ionic 4 app
+
```shell
npm run start
```

. Alternatively - Run as a mobile application in the Android emulator.
+
```shell
npm run ionic:android
```

. Or run as a PWA app
+
```shell
npm run ionic:pwa
```

NOTE: To connect to the local GraphQL server, when the app is running in the Android emulator,
change [Client URL](https://github.com/aerogear/ionic-showcase/blob/master/src/app/services/sync/voyager.service.ts#L76) from `localhost` to `10.0.2.2`. Note that Push notifications do not work in an emulator.

=== Adding integrations to the client

Client side is being configured dynamically by assets file located in `src/assets/config/config.js`.
Making changes in config can point client side application to remote server and add additional integrations for Push and Auth

Example config: 

```
window.showcaseConfig = {
  "backend": {
    "serverUrl": "http://yourserver/graphql",
    "wsServerUrl": "ws://yourserver/graphql"
  }
};
```


> NOTE: When running in cloud developers can swap this file dynamically using config-map or openshift secret

=== OpenShift Integration

To integrate with OpenShift mobile config please paste your configuration into
link:./src/mobile-services.js[mobile-services.js] file
