= AeroGear Data Sync Showcase Application

Example application using AeroGear Mobile Services.

== Implementation

Implementation includes:

- Integration with AeroGear Mobile Services
- Ionic 4 Angular frontend backed by Cordova
- A Node.js GraphQL Server that implements a sample `Tasks` workflow

=== GraphQL Client

The mobile application uses https://github.com/aerogear/aerogear-js-sdk/tree/master/packages/sync[Voyager Client] to provide additional offline capabilities on top of Apollo GraphQL.

=== GraphQL Server

The GraphQL server uses https://github.com/aerogear/voyager-server[Voyager Server] to provide GraphQL capabilities along with security, monitoring and tools to simplify GraphQL API development.

== Getting Started

Requirements:

- Docker
- Node.js 6.x or above to run server
- (optional) access to a running OpenShift instance

=== Running the server

. Start the PostgreSQL container
+
```shell
cd ./server
docker-compose up -d
```

. Start the server
+
```shell
npm install
npm run start
```
+
[NOTE]
====
If Keycloak integration is enabled on the server, and the Keycloak server is running using self-signed certificate, please make sure set this environment variable before running the server:

```shell
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
====

=== Running the Server on OpenShift (optional)

. Log into your OpenShift instance with the `oc login` command.
. Deploy the Server with PostgreSQL
+
```shell
oc new-app -f server/openshift-template.yml
```

. To deprovision all of the resources from the template, run
+
```shell
oc delete all -l app=ionic-showcase-server \
&& oc delete secret -l app=ionic-showcase-server \
&& oc delete pvc -l app=ionic-showcase-server
```

=== Running the Client

. Install Ionic 4
+
```shell
npm install -g ionic@4
```

. Install dependencies
+
```shell
npm install
```

. Browse Ionic 4 app
+
```shell
npm run start
```

. Alternatively - Run as a mobile application in the Android emulator.
+
```shell
npm run ionic:android
```

NOTE: To connect to the local GraphQL server, when the app is running in the Android emulator,
change [Client URL](https://github.com/aerogear/ionic-showcase/blob/master/src/app/services/sync/voyager.service.ts#L76) from `localhost` to `10.0.2.2`. Note that Push notifications do not work in an emulator.

=== OpenShift Integration

To integrate with OpenShift mobile config please paste your configuration into
link:./src/mobile-services.js[mobile-services.js] file
