= AeroGear Showcase Application

Example application using AeroGear Mobile Services.

== Implementation

Implementation includes:

- Integration with Datasync
- Ionic React frontend backed by Cordova
- A Node.js GraphQL Server that implements a sample `Tasks` workflow
- Authentication provided by Keycloak integration on the server and client side
- GraphQL Subscriptions backed by an MQTT broker

=== GraphQL Client

The mobile application uses https://github.com/aerogear/offix[Offix Client] to provide additional offline capabilities on top of Apollo GraphQL.

=== GraphQL Server

The GraphQL server uses https://github.com/aerogear/voyager-server[Voyager Server] to provide GraphQL capabilities along with security, monitoring and tools to simplify GraphQL API development.

== Getting Started

Requirements:

- Docker
- Node.js 12.x or above to run server
- (optional) access to a running OpenShift instance
- (optional) Keycloack server

=== Running the server

. Start the Postgres database and the MQTT broker
+
```shell
cd ./server
docker-compose up
```

. Start the server
+
```shell
npm install
npm run dev
```
+
[NOTE]
====
If Keycloak integration is enabled on the server, and the Keycloak server is running using self-signed certificate, please make sure set this environment variable before running the server:

```shell
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
====

=== Running the Server with the Keycloak Integration

Follow these instructions to set up Keycloak for Authentication/Authorization.


. Start Keycloak Server
+
```shell
cd server
npm run keycloak
```

. Configure the Keycloak Server
+
```shell
cd server
npm run keycloak:init
```

This command creates the necessary resources in Keycloak and prints instructions *you must follow to enable the integration.* 

Follow the instructions and copy the JSON configurations to the appropriate locations.
The showcase app and server will read these configurations and the integration will be enabled when they are started.

By default, two users that can log into the application are created.

- username: `developer`, password: `developer`
- username: `admin`, password: `admin`

==== Using the GraphQL playground with Keycloak

The GraphQL playground is available after a Keycloak login screen. Initially the following error will be displayed.

```
{
  "error": "Failed to fetch schema. Please check your connection"
}
```

The playground must be configured to send the Keycloak `Authorization` header with requests to the GraphQL server.

In the bottom left corner of the playground there is a field called **HTTP Headers** which will be added to requests sent by the playground.

Use `scripts/getToken.js` to get a valid header for the `developer` user.

The following script can be used to get a token for the default Keycloak credentials

```
cd server/scripts/keycloak
node getToken.js
```

Alternatively, the user-defined username and password can be passed into the script as arguments, as below

```
node getToken.js <username> <password>
```

The output will be in the form of a JSON object

```
{"Authorization":"Bearer <token string>"}
```

Copy the entire JSON object, then paste it into the HTTP Headers field in the playground. 
The error message should disappear and it is now possible to use the playground.

> NOTE: The GraphQL server is using a `public` Keycloak client to redirect browsers to the login page. This is useful for testing the server locally but **it is not recommended for production**. For production GraphQL server applications you should use a `bearer` client.

=== Running the Server on OpenShift 

. Log into your OpenShift instance with the `oc login` command.
. Deploy the Server with PostgreSQL
Templates can be found in https://github.com/aerogear/datasync-deployment repository.


+
```shell
git clone https://github.com/aerogear/datasync-deployment
cd datasync-deployment
oc new-app -f openshift/datasync-showcase.yml
```

. To deprovision all of the resources from the template, run
+
```shell
oc delete all -l app=ionic-showcase-server \
&& oc delete secret -l app=ionic-showcase-server \
&& oc delete pvc -l app=ionic-showcase-server
```

=== Running the Client

. Install Ionic
+
```shell
npm install -g @ionic/cli
```

. Install dependencies
+
```shell
npm install
```

. Start the app
+
```shell
npm run start
```

=== Adding keycloak integration to the client

Rename the `keycloak.example.json` to `keycloak.json`. Replace the contents of the file
with the keycloak json object generated during the keycloak integration init script.
 
[source,js]
----
{
  "realm": "<your realm>",
  "auth-server-url": "https://your-server/auth",
  "ssl-required": "none",
  "resource": "<your-client>",
  "public-client": true,
  "use-resource-role-mappings": true,
  "confidential-port": 0
}
----

> NOTE: When running in cloud, developers can swap this file dynamically using config-map or openshift secret
