= OpenVolunteerPlatform

*OpenVolunteerPlatform* is an open source project that builds a relief management mobile application using GraphQL. The app helps users organize distribution of food and mental health services for people affected by the quarantine restrictions.

== How the app works

*OpenVolunteerPlatform* is an progressive web application (PWA) that can be used by volunteers to collaborate and connect with vulnerable people. 

NOTE: The same leaflet can be used to gather possible volunteers. 

* The form is dynamically processed using data acqusition techniques to match people that are seeking assistance with those who are able to provide support. 
 
== Technical Details

The application includes:

* Integration with http://graphback.dev[Graphback] helps you generate your backend and client side queries based on user provided business models
- An example React application which uses the http://offix.dev[Offix client] to give you a fully featured offline experience
- Integration with Keycloak (SSO) for server and client authentication and user management
- GraphQL subscriptions backed by an MQTT broker(AMQ)

=== GraphQL Client

The mobile application uses https://github.com/aerogear/offix[Offix Client] to provide additional offline capabilities on top of Apollo GraphQL.

=== GraphQL Server

The GraphQL server uses https://github.com/aerogear/graphback[Graphback] to provide GraphQL capabilities.


