import { Db } from 'mongodb';

/**
 * findDailyAction handler generated by datashift cli
 */
export const createHandler = (db: Db, context: any) => {
    return async function (req: any, res: any) {
        const items = await db.collection("dailyactionplan").find().toArray();

        res.json({
            items,
            offset: 0,
            limit: items.length,
            count: items.length
        });
    }

}
