fragment TaskFields on Task { 
    id
    version
    title
    description
}


mutation createTask {
  createTask(title: "Task1" description: "test") {
     ...TaskFields
  }
}

mutation updateTask {
  updateTask(id: "1", title: "Task2", version: 1) {
    ...TaskFields
  }
}

mutation deleteTask {
  deleteTask(id: "1")
}

query getTask {
  getTask(id: "1") {
    ...TaskFields
  }
}

query allTasks {
  allTasks{
    ...TaskFields
  }
}

subscription taskModified {
  tasks {
    action
    task {
      ...TaskFields
    }
  }
}

subscription taskDeleted {
  tasks {
    action
    task {
      id
    }
  }
}

 query uploads{
    uploads{
      filename
      mimetype
      url
    }
  }