fragment TaskFields on Task { 
    id
    version
    title
    description
    status
}


mutation createTask {
  createTask(title: "Task1", description: "test", status: OPEN) {
     ...TaskFields
  }
}

mutation updateTask {
  updateTask(id: "1", title: "Task2", version: 1) {
    ...TaskFields
  }
}

mutation deleteTask {
  deleteTask(id: "1")
}

query getTask {
  getTask(id: "1") {
    ...TaskFields
  }
}

query allTasks {
  allTasks{
    ...TaskFields
  }
}

 query uploads{
    uploads{
      filename
      mimetype
      url
    }
  }
