= OpenVolunteerPlatform Starter

This project contains reference implementation for 
volunteer and admin application

== Project structure
- Volunteer Client application `/client`
- Admin application `/client-admin`
- Server application `/server`
- Data model representing system api `./model`
- OpenShift deployment `./openshift`

== Getting Started

Requirements:

- Docker and docker-compose
- https://nodejs.org/en/download/ (Node.js 12.x or above)
- (optional) access to a running OpenShift instance

=== Running Apps and Server

. Build client
+
```shell
yarn prepare:client
yarn prepare:admin
```
+

. Start the server
+
```shell
cd ./server
docker-compose up -d
## Wait at least minute for containers to start
yarn keycloak:init
yarn start
```

. Links to applications should be printed in console.
```shell
    🎮 Ionic PWA application available at http://localhost:4000
    🎮 Admin PWA application available at http://localhost:4000/admin
    🚀 GraphQL Playground is available at http://localhost:4000/graphql
````

By default, two users that can log into the application are created.

- username: `developer`, password: `developer`
- username: `admin`, password: `admin`

Volunteers can register to the application in login screen


==== Keycloak integration

Follow these instructions to set up Keycloak for Authentication/Authorization.

. Configure the Keycloak Server
+
```shell
cd ./server
yarn keycloak:init
```

This command creates the necessary resources in Keycloak and prints instructions *you must follow to enable the integration.* 

Follow the instructions and copy the JSON configurations to the appropriate locations.
The DataSync Starter app and server will read these configurations and the integration will be enabled when they are started.

By default, two users that can log into the application are created.

- username: `developer`, password: `developer`
- username: `admin`, password: `admin`


=== Running clients as Mobile Applications

==== For IOS
-----
cd ./client
yarn cap add ios
yarn run:ios
-----

==== For Android:
-----
cd ./client
yarn cap add android
yarn run:android
-----

When running locally you will need to also enable http traffic. 
For example for android add `android:usesCleartextTraffic="true"` to AndroidManifest.xml

Project should stard in IDE and can be launched as any other native application

== Using MQTT for GraphQL subscriptions

1. Go to server/scripts ./mqtt
2. Execute docker-compose up
3. Set MQTT_HOST environment variable in .env file

MQTT_HOST=127.0.0.1

=== Running On OpenShift

Please check link:./.openshift[.openshift] folder for more information.
