/**
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Query: {
    findTasks: (parent, args, context) => {
      return context.Task.findBy(args.fields)
    },
    findAllTasks: (parent, args, context) => {
      return context.Task.findAll()
    }
  },

  Mutation: {
    createTask: (parent, args, context) => {
      return context.Task.create(args.input, context)
    },
    updateTask: (parent, args, context) => {
      return context.Task.update(args.input, context)
    }
  }
}
